# Generated by Django 4.2.4 on 2023-12-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_alter_invoicedetail_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
